[package]
name = "fff-manager"
version = "0.1.0"
edition = "2021"


[dependencies]
confy = "0.6.0"
tracing = "0.1.40"
iced = "0.12.0"

# [profile.dev.package."*"]
# opt-level = 3

# [profile.dev]
# opt-level = 0
# codegen-units = 16
# lto = true
